name: Trigger auto deployment for ce

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ce-AutoDeployTrigger-53c3a5ba-716a-45bd-819f-7134ab4f1b76.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: dokerdl.azurecr.io
          registryUsername: ${{ secrets.CE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CE_REGISTRY_PASSWORD }}
          containerAppName: ce
          resourceGroup: ai-tools-rg
          imageToBuild: dokerdl.azurecr.io/ce:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


